name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run : python manage.py tests

Deploy:
  runs-on: ubuntu-latest
  needs: [build_and_test]
  steps:
    - name: echo hello world
      run: echo "Hellow world"



    