name: Build and Deploy

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare database
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Echo hello world
        run: echo "Hello world"
