name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate && python manage.py test

      - name: Run tests
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py tes   

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Echo hello world
        run: echo "Hello world"
